feat: profile edit be
ice-blockchain/ion-framework pull request #336
Opened 2024-11-26 17:59 UTC by ice-orion

## Description
This PR adds BE integration for the edit profile

## Additional Notes
* Adds `UserMetadataNotifier`, `BannerPickerNotifier`, change `AvatarPickerNotifier`
* Fixes edit profile UI, add loading states
* Adds `useDraftMetadata` hook to handle draft user state 

## Type of Change
- [x] Bug fix
- [x] New feature
- [ ] Breaking change
- [x] Refactoring
- [ ] Documentation
- [ ] Chore

## Screenshots 

https://github.com/user-attachments/assets/7af67b9a-631f-4bc0-a56a-850edf943f1b

2024-11-26 18:53 UTC, ice-kreios submitted a review, later dismissed

2024-11-27 08:14 UTC, ice-endymion requested changes

2024-11-27 08:14 UTC, ice-endymion commented on lib/app/features/user/providers/avatar_picker_notifier.dart
> +        state = const AvatarPickerState.initial();
Maybe we can show some messages to the user? 
If cropping or compression fails, the state reverts to initial, but the user is not informed, potentially leading to confusion.

2024-11-27 08:14 UTC, ice-endymion commented on lib/app/features/user/providers/banner_picker_notifier.dart
> +        state = const BannerPickerState.initial();
Also what about showing a message to the user about an error in cropping?

2024-11-27 10:13 UTC, ice-tychon commented on lib/app/features/auth/views/components/user_data_inputs/bio_input.dart
> +  const BioInput({this.controller, super.key, this.onChanged, this.initialValue});
No trailing comma and `super.*` must be in the end.

2024-11-27 10:30 UTC, ice-tychon commented on lib/app/features/user/pages/profile_edit_page/components/edit_submit_button/edit_submit_button.dart
> +              ref.watch(avatarPickerNotifierProvider).whenOrNull(processed: (file) => file);
It should be `ref.read`, the same for `bannerFile`.

2024-11-27 10:33 UTC, ice-tychon commented on lib/app/features/user/providers/user_metadata_notifier.dart
> +    return file != null
If you change return type `Future<({FileMetadata fileMeta, MediaAttachment attachment})?>` you'll be able to get rid of `uploadedAvatar.$2` above in the code.

2024-11-27 10:35 UTC, ice-tychon commented on lib/app/features/user/providers/user_metadata_notifier.dart
> +class UserMetadataNotifier extends _$UserMetadataNotifier {
Imho, the naming is poor in this file. `UserMetadataNotifier` and it's method `send` doesn't say what exactly they do. I'd name it something like `EditProfileNotifier`.

2024-11-27 11:13 UTC, ice-endymion submitted a review, later dismissed
LGTM 👌

2024-11-27 11:24 UTC, ice-tychon submitted a review, later dismissed

2024-11-27 11:41 UTC, ice-endymion approved these changes

2024-11-27 11:41 UTC, merged